services:
  web:
    build: app
    env_file:
      - .env
    environment:
      DEBUG: "FALSE"
    networks:
      - app_network
    volumes:
      - "./app:/app"
      - "media:/media"
      - "static:/static"
    depends_on:
      - db
    command: "gunicorn flipandfind.wsgi --workers ${GUNICORN_WORKERS} --bind 0.0.0.0:8000"
  db:
    image: "mysql:9"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - "db_data:/var/lib/mysql"
  nginx:
    image: "nginx:1"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "media:/media"
      - "static:/static"
    networks:
      - app_network
    depends_on:
      - web

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  media:
  static:
