services:
  web:
    build: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - "./app:/app"
      - "media:/media"
    depends_on:
      - db
  db:
    image: "mysql:9"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - "db_data:/var/lib/mysql"

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  media:
